### ISSUE TITLE
Gracefully handle stackoverflow on native platforms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [titzer/virgil#1]
```
When running on the JVM, a stack overflow manifests itself with a 
java.lang.StackOverflowError, which terminates the Virgil program. On native 
platforms, a stack overflow manifests itself by the program running past the 
end of the stack's mapped pages, causing a SIGSEGV (or SIGBUS), which cannot be 
handled by the runtime's signal handler (since there is no stack), resulting in 
termination of the program by the operating system.

Native platforms should check for stack overflow via one of the known 
mechanisms:

1. Use sigaltstack for signals
2. Stack banging
3. Explicit stack checks

Call graph analysis can likely eliminate most of #2 and #3 statically.
```

Original issue reported on code.google.com by `ben.tit...@gmail.com` on 28 Mar 2012 at 6:46

**Comment by titzer** [comment]
Turns out that I misunderstood Linux's stack segments. The stack segment created for the default thread is mapped with a special attribute `MAP_GROWSDOWN`, that cause the kernel to try to automatically grow the mapping upon page faults near the lower end of it. So it's not possible to reliably split the stack segment into a regular and alternate stack. The compiler will need to output another segment in the executable which it has full control over, and switch the stack pointer in the entry stub.

**Comment by titzer** [comment]
This is now implemented and in stable for x86-linux and x86-64-linux. The compiler emits its own stack segment if `-stack-size=N` is greater than `0`.

**Comment by titzer** [comment]
With https://github.com/titzer/virgil/commit/54630d7bac59e611c452acc2617a908d1c2091f8, stack overflow handling on x86-64-darwin now works. The only remaining platform is x86-darwin, the oldest of native platforms.

**Comment by titzer** [comment]
With https://github.com/titzer/virgil/commit/bd04778cd64eb73b05d8f2a07fd91f491fc21a89, this works on 32-bit MacOS, and with https://github.com/titzer/virgil/commit/8a930cd869163c5d680ad2c6d126bf6b51a20667, this is enabled for x86-64-darwin.

So I'll finally close this long-standing issue. Phew.
