### ISSUE TITLE
compile-time initialization System.puts error

### ISSUE THREAD

**Issue by diakopter** [titzer/virgil#42]
is it supposed to still work?

![image](https://user-images.githubusercontent.com/50262/109845161-70e14880-7c12-11eb-8a49-67cc31cf8765.png)

**Comment by titzer** [comment]
It looks like you are calling `System.puts` during compile-time initialization?

That's a problem because the compiler will resolve `System.puts` to the implementation in the Linux platform code and it tries to do things with pointers which are not allowed at compile time.

Can you tell me a little more about the use case?

**Comment by diakopter** [comment]
Not really. Just trying things out and copied the example from the tutorial (and wiki) docs. :)

Multiple stages is nice. Side effects not necessary. Curious about how nested data structures cross over from initialization to run-time.

**Comment by titzer** [comment]
Ah, thanks for pointing this out. I should update the wiki example.

**Comment by titzer** [comment]
By nested, you just mean an object graph? The compiler serializes everything reachable from the (used) component fields of the program after init. It traces the code starting from main and does tree shaking to toss everything not used.
