### ISSUE TITLE
Where to ask for help - slices / memcopy

### ISSUE THREAD

**Issue by travisstaloch** [titzer/virgil#49]
I'm having some fun making a tokenizer/parser and learning virgil.  Really enjoying the language so far.  Are there any community places such as irc or discord for questions?  

If not, i'm trying to answer these two questions:
- how to use `Pointer`s
- how to slice / get a substring of an array without making a copy

The usecase is basically just a `memcopy` from the end of an array to the beginning.  I tried using `Arrays.copy` and `Arrays.copyInto` but couldn't figure out how to slice the last n elements.  

And when I try to use something like `Pointer.atContents()` i'm getting an `UnresolvedIdentifier: identifier "Pointer" cannot be found`.  I looked and couldn't find a file where `Pointer` is defined.  :thinking:

**Comment by titzer** [comment]
Hi @travisstaloch,

I haven't gotten around to writing much in the way of tutorials, unfortunately. For `Pointer`s, your wandering into the platform-specific (actually native-only) code part, that is generally only for writing runtime code that must interface with, e.g. the kernel. However, that said, you can see some examples of code using `Pointer` under `rt/`. A brief synopsis:

- You can use `Pointer.NULL` to get the zero value
- You can add an `int` (`long` on 64-bit) to a `Pointer` to get another `Pointer`
- You can subtract two `Pointer` values to get an `int` (`long` on 64-bit)
- You can `.load<T>` a value of any (simple) type `T` from a `Pointer`'s memory location
- You can `.store<T>` a value of any (simple) type `T` to a `Pointer`'s memory location
- You can get a pointer to the contents of an array with `Pointer.atContents`
- You can get a pointer to the start of an object with `Pointer.atObject`
- You can get a pointer to an element of an array with `Pointer.atElement`
- You can get a pointer to a field in an object with `Pointer.atField`

The last few there are pretty dangerous; you would only need them if you are doing something very specific, like implementing a runtime system by generating new code. Otherwise, pointers are still very dangerous and should only be used, e.g. if you want to talk to a kernel.

You can define a data type that represents the slice of an array with 
```
type Slice<T>(array: Array<T>, offset: int, length: int)  {
   ...
}
```

Then you can define methods inside. Data types will (eventually) be unboxed--working on that now, so you can represent a slice of an array without an allocation. I'm considering adding language support for slices in the future.

Glad you like the language so far. There are some neat tricks you can do, but it will challenge you a bit.

Cheers!

**Comment by travisstaloch** [comment]
Ok thanks so much for the detailed explanation! I'm still getting feel for the language so this really helps me understand whats going on.  I now understand why using `Pointer`s would be dangerous.  Somehow I didn't realize there is a gc :facepalm: .  

I haven't seen the `type` keyword until now.  Guessing this `Slice` type above be like a struct with 3 fields.  Neat!  

Thanks again.  I will be following along and tinkering from time to time.  :+1:
